const { createElement, Fragment } = wp.element;
const { registerBlockType } = wp.blocks;
const { InspectorControls, useBlockProps, PanelColorSettings, RichText, URLInput } = wp.blockEditor;
const { PanelBody, SelectControl, RangeControl, ToggleControl, TextControl } = wp.components;
const { __ } = wp.i18n;

// Import icons data (will be generated by build process)
const icons = window.webentwicklerinIcons || {};

registerBlockType('webentwicklerin/icon', {
    edit: ({ attributes, setAttributes }) => {
        const {
            iconName,
            iconColor,
            backgroundColor,
            hoverIconColor,
            hoverBackgroundColor,
            width,
            height,
            linkUrl,
            linkTarget,
            linkRel,
            hasText,
            text,
            iconPosition,
            screenReaderOnly,
            gap,
        } = attributes;

        // Build inline styles
        const inlineStyles = {};

        // Icon-Farbe isoliert setzen, Textfarbe unverändert
        if (iconColor) {
            inlineStyles['--icon-base-color'] = iconColor;
        }
        if (backgroundColor) {
            inlineStyles.backgroundColor = backgroundColor;
        }
        if (hoverIconColor) {
            inlineStyles['--hover-icon-color'] = hoverIconColor;
        } else if (iconColor) {
            inlineStyles['--hover-icon-color'] = iconColor;
        }
        if (hoverBackgroundColor) {
            inlineStyles['--hover-bg-color'] = hoverBackgroundColor;
        } else if (backgroundColor) {
            inlineStyles['--hover-bg-color'] = backgroundColor;
        }
        if (gap && hasText) {
            inlineStyles.gap = gap;
        }

        const blockProps = useBlockProps({
            style: inlineStyles,
            className: `icon-position-${iconPosition} ${hasText ? 'has-text' : 'no-text'}`
        });

        const iconOptions = Object.keys(icons).map(key => ({
            label: key.charAt(0).toUpperCase() + key.slice(1).replace('-', ' '),
            value: key
        }));

        const currentIcon = icons[iconName] || '';

        return (
            <>
                <InspectorControls>
                    <PanelBody title={__('Icon Settings', 'webentwicklerin')} initialOpen={true}>
                        <SelectControl
                            label={__('Select Icon', 'webentwicklerin')}
                            value={iconName}
                            options={iconOptions}
                            onChange={(value) => setAttributes({ iconName: value })}
                        />

                        <RangeControl
                            label={__('Width (px)', 'webentwicklerin')}
                            value={parseInt(width)}
                            onChange={(value) => setAttributes({ width: value + 'px' })}
                            min={16}
                            max={200}
                        />

                        <RangeControl
                            label={__('Height (px)', 'webentwicklerin')}
                            value={parseInt(height)}
                            onChange={(value) => setAttributes({ height: value + 'px' })}
                            min={16}
                            max={200}
                        />
                    </PanelBody>

                    <PanelBody title={__('Link & Text', 'webentwicklerin')} initialOpen={false}>
                        <ToggleControl
                            label={__('Als Link verwenden', 'webentwicklerin')}
                            checked={!!linkUrl}
                            onChange={() => setAttributes({ linkUrl: linkUrl ? '' : '#' })}
                        />

                        {linkUrl && (
                            <>
                                <TextControl
                                    label={__('Link-URL', 'webentwicklerin')}
                                    value={linkUrl}
                                    onChange={(value) => setAttributes({ linkUrl: value })}
                                    placeholder="https://..."
                                />

                                <SelectControl
                                    label={__('Link öffnen in', 'webentwicklerin')}
                                    value={linkTarget}
                                    options={[
                                        { label: __('Gleiches Fenster', 'webentwicklerin'), value: '_self' },
                                        { label: __('Neues Fenster', 'webentwicklerin'), value: '_blank' },
                                    ]}
                                    onChange={(value) => setAttributes({
                                        linkTarget: value,
                                        linkRel: value === '_blank' ? 'noopener noreferrer' : ''
                                    })}
                                />
                            </>
                        )}

                        <ToggleControl
                            label={__('Text anzeigen', 'webentwicklerin')}
                            checked={hasText}
                            onChange={(value) => setAttributes({ hasText: value })}
                        />

                        {hasText && (
                            <>
                                <TextControl
                                    label={__('Text', 'webentwicklerin')}
                                    value={text}
                                    onChange={(value) => setAttributes({ text: value })}
                                />

                                <SelectControl
                                    label={__('Icon-Position', 'webentwicklerin')}
                                    value={iconPosition}
                                    options={[
                                        { label: __('Links vom Text', 'webentwicklerin'), value: 'left' },
                                        { label: __('Rechts vom Text', 'webentwicklerin'), value: 'right' },
                                        { label: __('Über dem Text', 'webentwicklerin'), value: 'top' },
                                        { label: __('Unter dem Text', 'webentwicklerin'), value: 'bottom' },
                                    ]}
                                    onChange={(value) => setAttributes({ iconPosition: value })}
                                />

                                <TextControl
                                    label={__('Abstand zwischen Icon und Text', 'webentwicklerin')}
                                    value={gap}
                                    onChange={(value) => setAttributes({ gap: value })}
                                    placeholder="0.5em"
                                    help={__('z.B. 0.5em, 8px, 1rem', 'webentwicklerin')}
                                />

                                <ToggleControl
                                    label={__('Text nur für Screenreader', 'webentwicklerin')}
                                    checked={screenReaderOnly}
                                    onChange={(value) => setAttributes({ screenReaderOnly: value })}
                                />
                            </>
                        )}
                    </PanelBody>

                    <PanelColorSettings
                        title={__('Farben', 'webentwicklerin')}
                        colorSettings={[
                            {
                                value: iconColor,
                                onChange: (newColor) => setAttributes({ iconColor: newColor }),
                                label: __('Icon-Farbe', 'webentwicklerin'),
                            },
                            {
                                value: backgroundColor,
                                onChange: (newColor) => setAttributes({ backgroundColor: newColor }),
                                label: __('Hintergrund', 'webentwicklerin'),
                            },
                        ]}
                    />

                    <PanelColorSettings
                        title={__('Hover-Farben', 'webentwicklerin')}
                        initialOpen={false}
                        colorSettings={[
                            {
                                value: hoverIconColor,
                                onChange: (newColor) => setAttributes({ hoverIconColor: newColor }),
                                label: __('Icon-Farbe bei Mauszeiger', 'webentwicklerin'),
                            },
                            {
                                value: hoverBackgroundColor,
                                onChange: (newColor) => setAttributes({ hoverBackgroundColor: newColor }),
                                label: __('Hintergrund bei Mauszeiger', 'webentwicklerin'),
                            },
                        ]}
                    />
                </InspectorControls>

                <div {...blockProps}>
                    {linkUrl ? (
                        <a href={linkUrl} target={linkTarget} rel={linkRel} className="wp-block-webentwicklerin-icon__link">
                            {hasText && text && iconPosition === 'top' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            <div
                                className="wp-block-webentwicklerin-icon__inner"
                                style={{ width: width, height: height }}
                                dangerouslySetInnerHTML={{ __html: currentIcon }}
                            />
                            {hasText && text && iconPosition === 'bottom' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                        </a>
                    ) : (
                        <>
                            {hasText && text && iconPosition === 'top' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            <div
                                className="wp-block-webentwicklerin-icon__inner"
                                style={{ width: width, height: height }}
                                dangerouslySetInnerHTML={{ __html: currentIcon }}
                            />
                            {hasText && text && iconPosition === 'bottom' && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                            {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                                <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                            )}
                        </>
                    )}
                </div>
            </>
        );
    },

    save: ({ attributes }) => {
        const {
            iconName,
            iconColor,
            backgroundColor,
            hoverIconColor,
            hoverBackgroundColor,
            width,
            height,
            linkUrl,
            linkTarget,
            linkRel,
            hasText,
            text,
            iconPosition,
            screenReaderOnly,
            gap,
        } = attributes;

        // Build inline styles for save
        const inlineStyles = {};

        if (iconColor) {
            inlineStyles['--icon-base-color'] = iconColor;
        }
        if (backgroundColor) {
            inlineStyles.backgroundColor = backgroundColor;
        }
        if (hoverIconColor) {
            inlineStyles['--hover-icon-color'] = hoverIconColor;
        } else if (iconColor) {
            inlineStyles['--hover-icon-color'] = iconColor;
        }
        if (hoverBackgroundColor) {
            inlineStyles['--hover-bg-color'] = hoverBackgroundColor;
        } else if (backgroundColor) {
            inlineStyles['--hover-bg-color'] = backgroundColor;
        }
        if (gap && hasText) {
            inlineStyles.gap = gap;
        }

        const blockProps = useBlockProps.save({
            style: inlineStyles,
            className: `icon-position-${iconPosition} ${hasText ? 'has-text' : 'no-text'}`
        });

        const currentIcon = icons[iconName] || '';

        return (
            <div {...blockProps}>
                {linkUrl ? (
                    <a href={linkUrl} target={linkTarget} rel={linkRel} className="wp-block-webentwicklerin-icon__link">
                        {hasText && text && iconPosition === 'top' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        <div
                            className="wp-block-webentwicklerin-icon__inner"
                            style={{ width: width, height: height }}
                            dangerouslySetInnerHTML={{ __html: currentIcon }}
                        />
                        {hasText && text && iconPosition === 'bottom' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                    </a>
                ) : (
                    <>
                        {hasText && text && iconPosition === 'top' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        <div
                            className="wp-block-webentwicklerin-icon__inner"
                            style={{ width: width, height: height }}
                            dangerouslySetInnerHTML={{ __html: currentIcon }}
                        />
                        {hasText && text && iconPosition === 'bottom' && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                        {hasText && text && (iconPosition === 'left' || iconPosition === 'right') && (
                            <span className={screenReaderOnly ? 'screen-reader-text' : 'icon-text'}>{text}</span>
                        )}
                    </>
                )}
            </div>
        );
    }
});

